#!/usr/bin/env python3
"""Build reproducible third-party notices from the locked Cargo graph and sources."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent


def render():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1", "--features", "bindings"],
        cwd=ROOT,
    ))
    packages = sorted(
        (p for p in metadata["packages"] if p["name"] != "keelocker-core"),
        key=lambda p: (p["name"], p["version"]),
    )
    texts = {}
    rows = []
    for package in packages:
        directory = Path(package["manifest_path"]).parent
        candidates = set()
        for path in directory.rglob("*"):
            if path.is_file() and path.name.upper().startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")):
                candidates.add(path)
        if package["license_file"]:
            candidates.add(directory / package["license_file"])
        if package["name"] == "r-efi":
            candidates.add(directory / "AUTHORS")
        if not candidates:
            fallback = ROOT / "licenses" / f'{package["name"]}-{package["version"]}.txt'
            if not fallback.is_file():
                fallback = ROOT / "licenses" / f'{package["license"]}.txt'
            if not fallback.is_file():
                raise RuntimeError(f'No license text for {package["name"]} {package["version"]}')
            candidates.add(fallback)
        refs = []
        for path in sorted(candidates):
            content = path.read_text(encoding="utf-8").replace("\r\n", "\n").strip()
            digest = hashlib.sha256(content.encode()).hexdigest()[:16]
            texts.setdefault(digest, content)
            refs.append(f'[{path.name}](#license-{digest})')
        name, version = package["name"], package["version"]
        source = f"https://crates.io/crates/{name}/{version}"
        if name == "keepass" and package["source"] is None:
            source = "vendor/keepass"
        rows.append(f'| [{name} {version}]({source}) | {package["license"]} | {", ".join(refs)} |')
    lines = [
        "# Third-party notices", "",
        "KeeLocker's own code is licensed under MIT; see [LICENSE](LICENSE).",
        "This file retains the licenses and notices supplied by the dependencies in Cargo.lock,",
        "including build, binding-generation, test and other-platform dependencies. Their licenses",
        "remain separate from KeeLocker's MIT license. Alternative licenses listed with OR remain alternatives.", "",
        "UniFFI and its runtime/template code use MPL 2.0. Their exact-version source is available",
        "through the crate links below. The generated bindings in KeeLocker/Data/Rust/Generated",
        "include UniFFI runtime/template code; the applicable third-party terms remain in force.",
        "The modified keepass source is included in vendor/keepass with its original MIT license.", "",
        "Generated by `python3 scripts/generate-notices.py` from cached, locked Cargo sources.",
        "Run `cargo fetch --locked` first when the cache is incomplete. Do not edit this file by hand.", "",
        "| Dependency and source | Declared license | Included texts |",
        "| --- | --- | --- |",
        *rows, "",
    ]
    for digest, content in sorted(texts.items()):
        lines.extend([f'<a id="license-{digest}"></a>', "", f"## License / notice {digest}", "", "```text", content, "```", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in notices differ")
    args = parser.parse_args()
    output = ROOT / "THIRD_PARTY_NOTICES.md"
    generated = render()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != generated:
            sys.exit("Third-party notices are stale; run python3 scripts/generate-notices.py")
        print("Third-party notices match the locked dependency sources.")
    else:
        output.write_text(generated, encoding="utf-8")
        print(f"Wrote {output.name}")


if __name__ == "__main__":
    main()
